import '../models/language_model.dart';

const String kPiperBase =
    'https://huggingface.co/rhasspy/piper-voices/resolve/v1.0.0';
const String kEspeakDataUrl =
    'https://github.com/k2-fsa/sherpa-onnx/releases/download/tts-models/espeak-ng-data.tar.bz2';

const List<LanguageModel> kAllLanguages = [
  // ── MAIN GROUP ─────────────────────────────────────────────────────────────
  LanguageModel(
    code: 'en-US',
    name: 'English (US)',
    nativeName: 'English (US)',
    flag: '🇺🇸',
    group: LanguageGroup.main,
    ttsEngine: TTSEngine.flutterTts,
    sttLocale: 'en-US',
    voices: [
      VoiceOption(
          id: 'system-en-US',
          label: 'System Voice',
          gender: 'neutral',
          quality: 'high',
          isSystem: true),
    ],
    endOfThoughtTrigger: 'done',
    endOfThoughtVariants: ['done', 'finished', 'that\'s it'],
    exitTrigger: 'goodbye',
    exitTriggerVariants: [
      'goodbye',
      'good bye',
      'farewell',
      'see you later',
      'take care'
    ],
  ),
  LanguageModel(
    code: 'en-GB',
    name: 'English (UK)',
    nativeName: 'English (UK)',
    flag: '🇬🇧',
    group: LanguageGroup.main,
    ttsEngine: TTSEngine.flutterTts,
    sttLocale: 'en-GB',
    voices: [
      VoiceOption(
          id: 'system-en-GB',
          label: 'System Voice',
          gender: 'neutral',
          quality: 'high',
          isSystem: true),
    ],
    endOfThoughtTrigger: 'done',
    endOfThoughtVariants: ['done', 'finished', 'that\'s it'],
    exitTrigger: 'goodbye',
    exitTriggerVariants: [
      'goodbye',
      'good bye',
      'farewell',
      'see you later',
      'take care'
    ],
  ),
  LanguageModel(
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    flag: '🇮🇳',
    group: LanguageGroup.main,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'hi',
    sttLocale: 'hi-IN',
    voices: [],
    endOfThoughtTrigger: 'हो गया',
    endOfThoughtVariants: ['हो गया', 'होगया', 'हो गिया', 'ho gaya', 'hogaya'],
    exitTrigger: 'अलविदा',
    exitTriggerVariants: [
      'अलविदा',
      'alvida',
      'अब चलता हूं',
      'अब चलती हूं',
      'जाना है'
    ],
  ),
  LanguageModel(
    code: 'hinglish',
    name: 'Hinglish',
    nativeName: 'Hinglish',
    flag: '🇮🇳',
    group: LanguageGroup.main,
    ttsEngine: TTSEngine.flutterTts,
    sttLocale: 'hi-IN',
    voices: [
      VoiceOption(
          id: 'system-hinglish',
          label: 'System Voice',
          gender: 'neutral',
          quality: 'high',
          isSystem: true),
    ],
    endOfThoughtTrigger: 'ho gaya',
    endOfThoughtVariants: ['ho gaya', 'hogaya', 'हो गया'],
    exitTrigger: 'alvida',
    exitTriggerVariants: ['alvida', 'अलविदा', 'goodbye', 'ab chalta hoon'],
  ),

  // ── NATIVE INDIAN GROUP ─────────────────────────────────────────────────────
  LanguageModel(
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'bn',
    sttLocale: 'bn-IN',
    voices: [],
    endOfThoughtTrigger: 'হয় গেছে',
    endOfThoughtVariants: ['হয় গেছে', 'হয়েছে', 'শেষ', 'hoise'],
    exitTrigger: 'বিদায়',
    exitTriggerVariants: ['বিদায়', 'আল্লাহ হাফেজ', 'আবার দেখা হবে'],
  ),
  LanguageModel(
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'pa',
    sttLocale: 'pa-IN',
    voices: [],
    endOfThoughtTrigger: 'ਹੋ ਗਿਆ',
    endOfThoughtVariants: ['ਹੋ ਗਿਆ', 'ਹੋਗਿਆ', 'ਪੂਰਾ', 'ho gia'],
    exitTrigger: 'ਅਲਵਿਦਾ',
    exitTriggerVariants: ['ਅਲਵਿਦਾ', 'alvida', 'ਫਿਰ ਮਿਲਾਂਗੇ'],
  ),
  LanguageModel(
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ta',
    sttLocale: 'ta-IN',
    voices: [],
    endOfThoughtTrigger: 'முடிந்தது',
    endOfThoughtVariants: ['முடிந்தது', 'முடிஞ்சு', 'செய்த', 'mudindru'],
    exitTrigger: 'வணக்கம்',
    exitTriggerVariants: ['வணக்கம்', 'கூட வணக்கம்', 'பிரிவோம்', 'vanakkam'],
  ),
  LanguageModel(
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'te',
    sttLocale: 'te-IN',
    voices: [],
    endOfThoughtTrigger: 'చేసాను',
    endOfThoughtVariants: ['చేసాను', 'చేసిన', 'సరியైనద', 'chesanu'],
    exitTrigger: 'అలవిడా',
    exitTriggerVariants: ['అలవిడా', 'నమస్కారం', 'మళ్ళీ కలుద్దాం', 'alvida'],
  ),
  LanguageModel(
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'kn',
    sttLocale: 'kn-IN',
    voices: [],
    endOfThoughtTrigger: 'ಮುಗಿಯಿತು',
    endOfThoughtVariants: ['ಮುಗಿಯಿತು', 'ಮುಗಿಯಾಗಿದೆ', 'ಹೋದ', 'mugiyitu'],
    exitTrigger: 'ವಿದಾಯ',
    exitTriggerVariants: ['ವಿದಾಯ', 'ಮತ್ತೆ ಭೇಟಿಯಾಗೋಣ', 'ನಮಸ್ಕಾರ', 'vidaya'],
  ),
  LanguageModel(
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ml',
    sttLocale: 'ml-IN',
    voices: [],
    endOfThoughtTrigger: 'സാധിച്ചു',
    endOfThoughtVariants: ['സാധിച്ചു', 'ചെയ്തു', 'പൂര്‍ത്തിയായി', 'sadhiccu'],
    exitTrigger: 'വിട',
    exitTriggerVariants: ['വിട', 'വിടപറയുന്നു', 'പോകണം', 'vida'],
  ),
  LanguageModel(
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'gu',
    sttLocale: 'gu-IN',
    voices: [],
    endOfThoughtTrigger: 'થઈ ગયું',
    endOfThoughtVariants: ['થઈ ગયું', 'સમાપ્ત', 'પૂર્ણ', 'thai gayu'],
    exitTrigger: 'અલવિદા',
    exitTriggerVariants: ['અલવિદા', 'વિદા', 'ફરી મળીશું', 'alvida'],
  ),
  LanguageModel(
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'mr',
    sttLocale: 'mr-IN',
    voices: [],
    endOfThoughtTrigger: 'झाले',
    endOfThoughtVariants: ['झाले', 'संपल', 'पूर्ण', 'zhale'],
    exitTrigger: 'अलविदा',
    exitTriggerVariants: ['अलविदा', 'निघतो', 'परत येतो', 'alvida'],
  ),
  LanguageModel(
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ur',
    sttLocale: 'ur-IN',
    voices: [],
    endOfThoughtTrigger: 'ہو گیا',
    endOfThoughtVariants: ['ہو گیا', 'ہوگیا', 'مکمل', 'ho gaya'],
    exitTrigger: 'الوداع',
    exitTriggerVariants: ['الوداع', 'خدا حافظ', 'پھر ملیں گے', 'alvida'],
  ),
  LanguageModel(
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'or',
    sttLocale: 'or-IN',
    voices: [],
    endOfThoughtTrigger: 'ହୋଇଗଲା',
    endOfThoughtVariants: ['ହୋଇଗଲା', 'ସମ୍ପୂର୍ଣ', 'ଶେଷ', 'hoigala'],
    exitTrigger: 'ବିଦାୟ',
    exitTriggerVariants: ['ବିଦାୟ', 'ଆଉ ଭଲ ଆସିବ', 'ଫେରି ଦେଖା ହୋଇବ', 'bidaya'],
  ),
  LanguageModel(
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'as',
    sttLocale: 'as-IN',
    voices: [],
    endOfThoughtTrigger: 'সমাপ্ত',
    endOfThoughtVariants: ['সমাপ্ত', 'শেষ', 'ঠিক আছে', 'samapot'],
    exitTrigger: 'বিদায়',
    exitTriggerVariants: ['বিদায়', 'আকৌ লগ পাম', 'যাওঁ আছোঁ', 'bidaya'],
  ),
  LanguageModel(
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'mai',
    sttLocale: 'mai-IN',
    voices: [],
    endOfThoughtTrigger: 'भोग गइल',
    endOfThoughtVariants: ['भोग गइल', 'संपूर्ण', 'अंत', 'bhog gail'],
    exitTrigger: 'विदा',
    exitTriggerVariants: ['विदा', 'फेर भेटब', 'जाइत छी', 'vida'],
  ),
  LanguageModel(
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    flag: '🇳🇵',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ne',
    sttLocale: 'ne-NP',
    voices: [],
    endOfThoughtTrigger: 'भएको छ',
    endOfThoughtVariants: ['भएको छ', 'सकिएको छ', 'खत्म', 'bhaeko cha'],
    exitTrigger: 'अलविदा',
    exitTriggerVariants: ['अलविदा', 'फेरि भेटौंला', 'जानु पर्छ', 'alvida'],
  ),
  LanguageModel(
    code: 'si',
    name: 'Sinhala',
    nativeName: 'සිංහල',
    flag: '🇱🇰',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'si',
    sttLocale: 'si-LK',
    voices: [],
    endOfThoughtTrigger: 'සිදුවිණි',
    endOfThoughtVariants: ['සිදුවිණි', 'අවසන්', 'ඉවරයි', 'siduvi'],
    exitTrigger: 'ගිහින් සිටින්න',
    exitTriggerVariants: [
      'ගිහින් සිටින්න',
      'නැවත හමුවෙමු',
      'යනවා',
      'gihin sitinna'
    ],
  ),
  LanguageModel(
    code: 'sa',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'sa',
    sttLocale: 'sa-IN',
    voices: [],
    endOfThoughtTrigger: 'समृद्धम्',
    endOfThoughtVariants: ['समृद्धम्', 'समाप्तम्', 'पूर्णम्', 'samriddham'],
    exitTrigger: 'विदा',
    exitTriggerVariants: ['विदा', 'पुनर्दर्शनम्', 'गमिष्यामि', 'vida'],
  ),
  LanguageModel(
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'کٲشُر',
    flag: '🇮🇳',
    group: LanguageGroup.nativeIndian,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ks',
    sttLocale: 'ks-IN',
    voices: [],
    endOfThoughtTrigger: 'مکمل ہویا',
    endOfThoughtVariants: ['مکمل ہویا', 'ختم', 'اختتام', 'mukamil hua'],
    exitTrigger: 'خدا حافظ',
    exitTriggerVariants: ['خدا حافظ', 'پھر اچھُ', 'وِچھرِنٛ', 'khuda hafiz'],
  ),

  // ── INTERNATIONAL GROUP ─────────────────────────────────────────────────────
  LanguageModel(
    code: 'fr',
    name: 'French',
    nativeName: 'Français',
    flag: '🇫🇷',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'fr',
    sttLocale: 'fr-FR',
    voices: [],
    endOfThoughtTrigger: 'fait',
    endOfThoughtVariants: ['fait', 'c\'est bon', 'terminé'],
    exitTrigger: 'au revoir',
    exitTriggerVariants: ['au revoir', 'à bientôt', 'adieu', 'à la prochaine'],
  ),
  LanguageModel(
    code: 'de',
    name: 'German',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'de',
    sttLocale: 'de-DE',
    voices: [],
    endOfThoughtTrigger: 'fertig',
    endOfThoughtVariants: ['fertig', 'erledigt', 'done'],
    exitTrigger: 'auf Wiedersehen',
    exitTriggerVariants: ['auf Wiedersehen', 'tschüss', 'adieu', 'wiedersehen'],
  ),
  LanguageModel(
    code: 'es',
    name: 'Spanish',
    nativeName: 'Español',
    flag: '🇪🇸',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'es',
    sttLocale: 'es-ES',
    voices: [],
    endOfThoughtTrigger: 'listo',
    endOfThoughtVariants: ['listo', 'hecho', 'terminado'],
    exitTrigger: 'adiós',
    exitTriggerVariants: [
      'adiós',
      'hasta luego',
      'hasta la vista',
      'nos vemos'
    ],
  ),
  LanguageModel(
    code: 'it',
    name: 'Italian',
    nativeName: 'Italiano',
    flag: '🇮🇹',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'it',
    sttLocale: 'it-IT',
    voices: [],
    endOfThoughtTrigger: 'fatto',
    endOfThoughtVariants: ['fatto', 'pronto', 'finito'],
    exitTrigger: 'arrivederci',
    exitTriggerVariants: [
      'arrivederci',
      'addio',
      'alla prossima',
      'ci vediamo'
    ],
  ),
  LanguageModel(
    code: 'pt-BR',
    name: 'Portuguese (BR)',
    nativeName: 'Português',
    flag: '🇧🇷',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'pt-BR',
    sttLocale: 'pt-BR',
    voices: [],
    endOfThoughtTrigger: 'pronto',
    endOfThoughtVariants: ['pronto', 'feito', 'terminado'],
    exitTrigger: 'adeus',
    exitTriggerVariants: ['adeus', 'até logo', 'até mais', 'tchau tchau'],
  ),
  LanguageModel(
    code: 'ru',
    name: 'Russian',
    nativeName: 'Русский',
    flag: '🇷🇺',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ru',
    sttLocale: 'ru-RU',
    voices: [],
    endOfThoughtTrigger: 'готово',
    endOfThoughtVariants: ['готово', 'сделано', 'готовий'],
    exitTrigger: 'до свидания',
    exitTriggerVariants: ['до свидания', 'пока пока', 'прощай', 'до встречи'],
  ),
  LanguageModel(
    code: 'nl',
    name: 'Dutch',
    nativeName: 'Nederlands',
    flag: '🇳🇱',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'nl',
    sttLocale: 'nl-NL',
    voices: [],
    endOfThoughtTrigger: 'klaar',
    endOfThoughtVariants: ['klaar', 'gedaan', 'voltooid'],
    exitTrigger: 'tot ziens',
    exitTriggerVariants: ['tot ziens', 'vaarwel', 'tot later', 'dag dag'],
  ),
  LanguageModel(
    code: 'pl',
    name: 'Polish',
    nativeName: 'Polski',
    flag: '🇵🇱',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'pl',
    sttLocale: 'pl-PL',
    voices: [],
    endOfThoughtTrigger: 'gotowe',
    endOfThoughtVariants: ['gotowe', 'zrobione', 'skończone'],
    exitTrigger: 'do widzenia',
    exitTriggerVariants: ['do widzenia', 'żegnaj', 'do zobaczenia', 'pa pa'],
  ),
  LanguageModel(
    code: 'uk',
    name: 'Ukrainian',
    nativeName: 'Українська',
    flag: '🇺🇦',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'uk',
    sttLocale: 'uk-UA',
    voices: [],
    endOfThoughtTrigger: 'готово',
    endOfThoughtVariants: ['готово', 'зроблено', 'готовий'],
    exitTrigger: 'до побачення',
    exitTriggerVariants: ['до побачення', 'пока пока', 'на все добре', 'бувай'],
  ),
  LanguageModel(
    code: 'sv',
    name: 'Swedish',
    nativeName: 'Svenska',
    flag: '🇸🇪',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'sv',
    sttLocale: 'sv-SE',
    voices: [],
    endOfThoughtTrigger: 'klart',
    endOfThoughtVariants: ['klart', 'färdig', 'gjort'],
    exitTrigger: 'hej då',
    exitTriggerVariants: ['hej då', 'farväl', 'adjö', 'vi ses'],
  ),
  LanguageModel(
    code: 'nb',
    name: 'Norwegian',
    nativeName: 'Norsk',
    flag: '🇳🇴',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'nb',
    sttLocale: 'nb-NO',
    voices: [],
    endOfThoughtTrigger: 'ferdig',
    endOfThoughtVariants: ['ferdig', 'gjort', 'klar'],
    exitTrigger: 'ha det',
    exitTriggerVariants: ['ha det', 'farvel', 'adjø', 'vi ses'],
  ),
  LanguageModel(
    code: 'fi',
    name: 'Finnish',
    nativeName: 'Suomi',
    flag: '🇫🇮',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'fi',
    sttLocale: 'fi-FI',
    voices: [],
    endOfThoughtTrigger: 'valmis',
    endOfThoughtVariants: ['valmis', 'tehty', 'valmiina'],
    exitTrigger: 'näkemiin',
    exitTriggerVariants: [
      'näkemiin',
      'heippa heippa',
      'moikka moikka',
      'nähdään'
    ],
  ),
  LanguageModel(
    code: 'cs',
    name: 'Czech',
    nativeName: 'Čeština',
    flag: '🇨🇿',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'cs',
    sttLocale: 'cs-CZ',
    voices: [],
    endOfThoughtTrigger: 'hotovo',
    endOfThoughtVariants: ['hotovo', 'hotovo', 'uděláno'],
    exitTrigger: 'na shledanou',
    exitTriggerVariants: ['na shledanou', 'sbohem', 'majte se', 'hezký den'],
  ),
  LanguageModel(
    code: 'tr',
    name: 'Turkish',
    nativeName: 'Türkçe',
    flag: '🇹🇷',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'tr',
    sttLocale: 'tr-TR',
    voices: [],
    endOfThoughtTrigger: 'bitti',
    endOfThoughtVariants: ['bitti', 'tamamlandı', 'hazır'],
    exitTrigger: 'hoşça kalın',
    exitTriggerVariants: [
      'hoşça kalın',
      'allahaismarladık',
      'güle güle',
      'görüşmek üzere'
    ],
  ),
  LanguageModel(
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    flag: '🇻🇳',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'vi',
    sttLocale: 'vi-VN',
    voices: [],
    endOfThoughtTrigger: 'xong',
    endOfThoughtVariants: ['xong', 'hoàn thành', 'được rồi'],
    exitTrigger: 'tạm biệt',
    exitTriggerVariants: [
      'tạm biệt',
      'hẹn gặp lại',
      'chào tạm biệt',
      'tôi đi nhé'
    ],
  ),
  LanguageModel(
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    flag: '🇨🇳',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'zh',
    sttLocale: 'zh-CN',
    voices: [],
    endOfThoughtTrigger: '完成',
    endOfThoughtVariants: ['完成', '做完', '好了'],
    exitTrigger: '再见',
    exitTriggerVariants: ['再见', '拜拜', '下次见', '保重'],
  ),
  LanguageModel(
    code: 'ja',
    name: 'Japanese',
    nativeName: '日本語',
    flag: '🇯🇵',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ja',
    sttLocale: 'ja-JP',
    voices: [],
    endOfThoughtTrigger: '終了',
    endOfThoughtVariants: ['終了', '終わった', 'おしまい'],
    exitTrigger: 'さようなら',
    exitTriggerVariants: ['さようなら', 'じゃあね', 'またね', 'お疲れ様'],
  ),
  LanguageModel(
    code: 'ko',
    name: 'Korean',
    nativeName: '한국어',
    flag: '🇰🇷',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ko',
    sttLocale: 'ko-KR',
    voices: [],
    endOfThoughtTrigger: '완료',
    endOfThoughtVariants: ['완료', '끝났어', '끝'],
    exitTrigger: '안녕히',
    exitTriggerVariants: ['안녕히', '또 봐요', '다음에 봐요', '잘 가요'],
  ),
  LanguageModel(
    code: 'ar',
    name: 'Arabic',
    nativeName: 'العربية',
    flag: '🇸🇦',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'ar',
    sttLocale: 'ar-SA',
    voices: [],
    endOfThoughtTrigger: 'انتهى',
    endOfThoughtVariants: ['انتهى', 'خلص', 'تم'],
    exitTrigger: 'وداعا',
    exitTriggerVariants: ['وداعا', 'إلى اللقاء', 'مع السلامة', 'في أمان الله'],
  ),
  LanguageModel(
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa',
    flag: '🇮🇩',
    group: LanguageGroup.international,
    ttsEngine: TTSEngine.sherpaOnnxEspeak,
    espeakVoice: 'id',
    sttLocale: 'id-ID',
    voices: [],
    endOfThoughtTrigger: 'selesai',
    endOfThoughtVariants: ['selesai', 'selesai', 'beres'],
    exitTrigger: 'selamat tinggal',
    exitTriggerVariants: [
      'selamat tinggal',
      'sampai jumpa',
      'selamat jalan',
      'dada dada'
    ],
  ),
];
